# Generated by Django 4.2.7 on 2025-10-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("capacity", models.PositiveIntegerField(verbose_name="Вместимость")),
                ("floor", models.PositiveIntegerField(default=1, verbose_name="Этаж")),
                (
                    "equipment",
                    models.TextField(blank=True, verbose_name="Оборудование"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="rooms/", verbose_name="Фото"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Зал",
                "verbose_name_plural": "Залы",
                "ordering": ["floor", "name"],
            },
        ),
    ]
