# Generated by Django 4.2.7 on 2025-11-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_profile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.CharField(
                choices=[
                    ("avatar1.png", "Аватар 1 - Спортсмен"),
                    ("avatar2.png", "Аватар 2 - Гимнаст"),
                    ("avatar3.png", "Аватар 3 - Боксёр"),
                    ("avatar4.png", "Аватар 4 - Йог"),
                    ("avatar5.png", "Аватар 5 - Фитнес"),
                    ("avatar6.png", "Аватар 6 - Силач"),
                    ("avatar7.png", "Аватар 7 - Бегун"),
                    ("avatar8.png", "Аватар 8 - Пловец"),
                ],
                default="avatar1.png",
                max_length=20,
                verbose_name="Аватар",
            ),
        ),
    ]
