# Generated by Django 4.2.7 on 2025-11-17 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("WEIGHT_LOSS", "Похудение"),
                            ("MUSCLE_GAIN", "Набор мышечной массы"),
                            ("ENDURANCE", "Выносливость"),
                            ("FLEXIBILITY", "Гибкость"),
                            ("GENERAL_FITNESS", "Общая физическая подготовка"),
                            ("STRENGTH", "Силовые показатели"),
                        ],
                        default="GENERAL_FITNESS",
                        max_length=50,
                        verbose_name="Цель",
                    ),
                ),
                (
                    "fitness_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Начальный"),
                            ("INTERMEDIATE", "Средний"),
                            ("ADVANCED", "Продвинутый"),
                        ],
                        default="BEGINNER",
                        max_length=20,
                        verbose_name="Уровень подготовки",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        help_text="Ограничения, предпочтения, заболевания",
                        verbose_name="Дополнительная информация",
                    ),
                ),
                (
                    "workout_content",
                    models.TextField(
                        help_text="Сгенерированная AI программа в формате Markdown",
                        verbose_name="Программа тренировок",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создан"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_plans",
                        to="accounts.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа тренировок",
                "verbose_name_plural": "Программы тренировок",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("WEIGHT_LOSS", "Похудение"),
                            ("MUSCLE_GAIN", "Набор мышечной массы"),
                            ("ENDURANCE", "Выносливость"),
                            ("FLEXIBILITY", "Гибкость"),
                            ("GENERAL_FITNESS", "Общая физическая подготовка"),
                            ("STRENGTH", "Силовые показатели"),
                        ],
                        default="GENERAL_FITNESS",
                        max_length=50,
                        verbose_name="Цель",
                    ),
                ),
                (
                    "dietary_preferences",
                    models.TextField(
                        blank=True,
                        help_text="Вегетарианство, аллергии, предпочтения",
                        verbose_name="Диетические предпочтения",
                    ),
                ),
                (
                    "nutrition_content",
                    models.TextField(
                        help_text="Сгенерированный AI план в формате Markdown",
                        verbose_name="План питания",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создан"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_plans",
                        to="accounts.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "План питания",
                "verbose_name_plural": "Планы питания",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ AI")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создан"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chats",
                        to="accounts.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "workout_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to="accounts.workoutplan",
                        verbose_name="Программа тренировок",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI диалог",
                "verbose_name_plural": "AI диалоги",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workoutplan",
            index=models.Index(
                fields=["client", "-created_at"], name="accounts_wo_client__c7cc8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutplan",
            index=models.Index(
                fields=["is_active"], name="accounts_wo_is_acti_bd030b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nutritionplan",
            index=models.Index(
                fields=["client", "-created_at"], name="accounts_nu_client__151de4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nutritionplan",
            index=models.Index(
                fields=["is_active"], name="accounts_nu_is_acti_df7d55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichat",
            index=models.Index(
                fields=["client", "created_at"], name="accounts_ai_client__72843f_idx"
            ),
        ),
    ]
