# Generated by Django 4.2.7 on 2025-10-31 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Длительность (минут)"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="class_types/",
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Тип занятия",
                "verbose_name_plural": "Типы занятий",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="Дата и время")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(verbose_name="Длительность (минут)"),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(verbose_name="Максимум мест"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Запланировано"),
                            ("IN_PROGRESS", "Идёт"),
                            ("COMPLETED", "Завершено"),
                            ("CANCELLED", "Отменено"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="classes.classtype",
                        verbose_name="Тип занятия",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="facilities.room",
                        verbose_name="Зал",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="accounts.trainer",
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Занятие",
                "verbose_name_plural": "Занятия",
                "ordering": ["datetime"],
            },
        ),
    ]
